/* eslint-disable react/react-in-jsx-scope */
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";

import AuthProvider from "@/components/AuthProvider";
import Providers from "./Redux/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full ">
      <AuthProvider>
        <body className="h-full bg-white">
          <Navbar />

          <Providers>{children}</Providers>
        </body>
      </AuthProvider>
    </html>
  );
}
